version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: 'always'
    environment:
      - REDIS_HOST=redis-18756.c244.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=18756
      - REDIS_PASSWORD=3BiPvGGG2Ag0vOcchICZ2IaMmXveFz0L
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
